#!/usr/bin/env bash
#using while in bash 
x=1
while [ $x  -le 10 ]
do
        if [ $x -ne 9 ]
        then
                echo "Best School"
        else
                echo "Hi"
        fi
        x=$(( x + 1 ))
done
